### ISSUE TITLE
Update the dependencies

### ISSUE THREAD

**Issue by hardBSDk** [TheAwiteb/data2sound#10]
Update the dependencies to the latest version.

**Comment by TheAwiteb** [comment]
It is dependency free, what do you mean? 

https://github.com/TheAwiteb/data2sound/blob/master/Cargo.toml#L17-L18

**Comment by TheAwiteb** [comment]
Ok, I think you mean nothing.

**Comment by hardBSDk** [comment]
@TheAwiteb Sorry, I forgot to verify if it was dependency-free.

I though this because most Rust programs use third-party libraries and your program is a little old.
