### ISSUE TITLE
Strip the header

### ISSUE THREAD

**Issue by TheAwiteb** [TheAwiteb/data2sound#3]
Our wave file is two section, the first section is the wave header (44 bytes) and second section is the original file data. And the decoding process taking long than encoding (x2 [`benchmarks`](https://github.com/TheAwiteb/data2sound/tree/e37840df6c60f1a2fb036d3ed7f0e48e275a0568#benchmarks)). I think is better to strip it and rewrite the data to the output file. @Amjad50 what do you think?

My prototype of strip way with 2.7 GB
> Executed in    4.79 secs    fish           external
   usr time    3.17 secs  550.00 micros    3.17 secs
   sys time    1.54 secs  353.00 micros    1.54 secs

Current way with 2.7 GB
> Executed in   12.62 secs    fish           external
   usr time   11.04 secs  472.00 micros   11.04 secs
   sys time    1.54 secs  279.00 micros    1.54 secs

**Comment by Amjad50** [comment]
Nice performance boost
